<a href="https://colab.research.google.com/github/abdul-majeed1/python-for-data-analysis/blob/main/Python_For_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Variables**

In [ ]:
# It stores name, number, float.

In [ ]:
name = 'Abdul Majeed'
print(name)

Abdul Majeed

In [ ]:
age = 25
print(age)

25

In [ ]:
type(age)

int

In [ ]:
height = 5.9
type(height)

float

# **2. List**

In [ ]:
# Store group of items.

In [ ]:
me = ['Abdul Majeed', 25, 5.9]
print(me)

['Abdul Majeed', 25, 5.9]

In [ ]:
me[0]

'Abdul Majeed'

In [ ]:
me.append("Pakistan")

In [ ]:
me

['Abdul Majeed', 25, 5.9, 'Pakistan']

In [ ]:
me.remove(5.9)

In [ ]:
me

['Abdul Majeed', 25, 'Pakistan']

# **3. Tuples**

In [ ]:
# storer values but in immutable manner.

In [ ]:
x = (15, 20)

In [ ]:
type(x)

tuple

In [ ]:
x[1]

20

# **4. Dictionaries**

In [ ]:
p = {"Name" : "Abdul Majeed", "Age" : 25, "Country" : "Pakistan"}

In [ ]:
type(p)

dict

In [ ]:
p["Name"]

'Abdul Majeed'

In [ ]:
p['Name'] = 'Abdul Majeed'

In [ ]:
p

{'Name': 'Abdul Majeed', 'Age': 25, 'Country': 'Pakistan'}

In [ ]:
p["Height"] = 5.9

In [ ]:
p

{'Name': 'Abdul Majeed', 'Age': 25, 'Country': 'Pakistan', 'Height': 5.9}

# **5. Loops**

## **1. For Loop : known iterations**

In [ ]:
sum = 0
for i in range(1, 11):
  sum += i

print(sum)

55

## **2. While Loop: until is a condition met.**

In [ ]:
sum = 0
i = 0
while(i < 6):
  sum += i
  i += 1

print(sum)

15

# **6. Functions**

In [ ]:
# avoids code repetition
# reuse the code any number of times
# simply need to call the function

In [ ]:
# adding 2 numbers:

def add_numbers(a,b):
  return a+b

In [ ]:
add_numbers(10, 17)

27

In [ ]:
add_numbers(23,41)

64

In [ ]:
add_numbers(323,432)

755

# **7. NUMPY**

In [ ]:
# NumPy is a Python library used for fast mathematical calculations on large numeric data.

In [ ]:
import numpy as np

In [ ]:
# numpy accepts same data type only
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **Dimensions of arrays**

In [ ]:
# 0 Dimension (Scalar): single value
arr = np.array(25)
arr.ndim

0

In [ ]:
# 1 Dimension (Vector): values in one line
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.ndim

1

In [ ]:
# 2 Dimension (Matrix): rows and columns
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr.ndim

2

In [ ]:
# 3 Dimension (Tensor / Cube): multiple layers of rows and columns
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 2 layers, 2 rows, 3 columns
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## **Array Creation & Random Numbers**

In [ ]:
# np.arange(): It makes a list of numbers from start to stop with a step.

In [ ]:
a = np.arange(1, 10) # start, stop
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(1, 10, 2) # start, stop, step
a

array([1, 3, 5, 7, 9])

In [ ]:
# np.linspace(): It makes a list of numbers evenly spaced between start and stop.

In [ ]:
a = np.linspace(0, 1, 11) # start, stop, Number of values
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
# np.logspace(): It makes numbers spaced evenly on a logarithmic scale between 10^start and 10^stop.

In [ ]:
a = np.logspace(1, 3, 3) # logarithmic scale array -> 10^1, 10^3, ... 3 points
a

array([  10.,  100., 1000.])

In [ ]:
# np.zeros(): It creates a NumPy array filled with zeros.

In [ ]:
# 0D array: single zero value
a = np.zeros(())
a
a.ndim

0

In [ ]:
# 1D array: zeros in one line
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# 2D array: zeros in rows and columns
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 3D array: zeros in layers
a = np.zeros((3,2,3)) #2 layers → each has 2 rows → each row has 2 zeros
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# np.ones(): It creates a NumPy array filled with 1s.

In [ ]:
# 0D (single value)
a = np.ones(())
a

array(1.)

In [ ]:
# 1D (line of ones)
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
# 2D (rows & columns)
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 3D (layers)
a = np.ones((2,3,2)) # (layers, rows, columns)
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# np.full(): It creates a NumPy array of any shape, filled with the value you want.

In [ ]:
# 0D example (single value)
a = np.full((), 7)
a

array(7)

In [ ]:
# 1D (line of same value)
a = np.full(10, 2)
a

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# 2D (rows & columns)
a = np.full((4,3), 4) # 4 rows, 3 columns of 4
a

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
# 3D (layers, rows, columns)
a = np.full((3,2,3), 5) # 3 layers, 2 rows, 3 columns of 5
a

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [ ]:
# np.empty(): It creates a NumPy array of given shape but does NOT initialize the values (they can be random garbage values).

In [ ]:
# 0D (single value, uninitialized)
a = np.empty([])
a

array(2.5e-323)

In [ ]:
# 1D (line, uninitialized)
a = np.empty(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
# 2D (rows & columns, uninitialized)
a = np.empty([4,2])
a

array([[9.87388009e-316, 0.00000000e+000],
       [0.00000000e+000, 3.05974854e-320],
       [6.91925138e-310, 6.91925138e-310],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
# 3D (layers, rows, columns, uninitialized)
a = np.empty([3, 2, 3])
a

array([[[1.09602320e-315, 0.00000000e+000, 6.91923007e-310],
        [6.91923007e-310, 6.91923007e-310, 5.28035228e-317]],

       [[6.91923007e-310, 6.91923007e-310, 6.91923007e-310],
        [6.91923007e-310, 6.91923007e-310, 6.91923007e-310]],

       [[6.91923020e-310, 6.91923014e-310, 5.37016946e-317],
        [6.91923035e-310, 6.91923015e-310, 6.91923015e-310]]])

In [ ]:
# np.random.rand(): It creates an array of given shape filled with random numbers between 0 and 1.

In [ ]:
# 0D (single random number)
a = np.random.rand() # no shape given → single number
a

0.6385210387566268

In [ ]:
# 1D (line of random numbers)
a = np.random.rand(5) # 5 random numbers
a

array([0.80466817, 0.67851991, 0.40404293, 0.16830392, 0.5672828 ])

In [ ]:
# 2D (rows & columns)
a = np.random.rand(2, 3) # 2 rows & 3 columns
a

array([[0.38221552, 0.54686173, 0.23973478],
       [0.68164908, 0.96443648, 0.10940311]])

In [ ]:
# 3D (layers, rows, columns)
a = np.random.rand(3, 2, 3) # 3 layers, 2 rows, 3 columns
a

array([[[0.23303156, 0.56010373, 0.05514407],
        [0.30154906, 0.49614535, 0.10714733]],

       [[0.18314903, 0.85012908, 0.32766561],
        [0.77015326, 0.36976006, 0.81905192]],

       [[0.82181539, 0.71907563, 0.08983773],
        [0.02361477, 0.07192162, 0.40744137]]])

In [ ]:
# np.random.randn(): It creates an array of random numbers from a standard normal distribution (mean = 0, std = 1).

In [ ]:
# 0D (single random number)
a = np.random.randn()
a

-0.23444386369529807

In [ ]:
# 1D (line of random numbers)
a = np.random.randn(3)
a

array([-1.65473098,  0.72936582,  1.70139268])

In [ ]:
# 2D (rows & columns)
a = np.random.randn(2, 3) # 2 rows & 3 columns
a

array([[-1.52484507, -0.02396024,  0.0841564 ],
       [-1.00169494, -0.27328166, -0.500924  ]])

In [ ]:
# 3D (layers, rows, columns)
a = np.random.randn(2, 2, 3) # 2 layers, 2 rows, 3 columns
a

array([[[-0.99875533, -1.63051858,  0.43239476],
        [ 1.03871145, -0.10942958, -1.85095971]],

       [[ 0.35451032, -0.60149   , -0.71395319],
        [-0.31149913, -0.14640494, -1.28314319]]])

In [ ]:
# np.random.randint(): It creates random integers in a given range [low, high)

In [ ]:
# 0D (single random integer)
a = np.random.randint(1, 10)
a

7

In [ ]:
# 1D (line of random integers)
a = np.random.randint(1, 10, 5) # line of 5 random integers
a

array([2, 7, 7, 1, 6])

In [ ]:
# 2D (rows & columns)
a = np.random.randint(1, 10, (2, 3))
a

array([[3, 8, 3],
       [2, 5, 3]])

In [ ]:
# 3D (layers, rows, columns)
a = np.random.randint(1, 10, (2, 2, 2))
a

array([[[7, 9],
        [2, 5]],

       [[4, 4],
        [1, 9]]])

## **Data Types**

In [ ]:
a = np.array([0, 1, 2, 3.3, 4, 5, 6, 7, 8, 9])
a

array([0. , 1. , 2. , 3.3, 4. , 5. , 6. , 7. , 8. , 9. ])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>

In [ ]:
a = ["Abdul Majeed", 25, 5,9]
b = np.array(a)
b

array(['Abdul Majeed', '25', '5', '9'], dtype='<U21')

In [ ]:
a = np.array([0, 1, 2, 3, 4.2, 5, 6])
a

array([0. , 1. , 2. , 3. , 4.2, 5. , 6. ])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array(["0", 1, 2, 3, 4, 5, 6])
a

array(['0', '1', '2', '3', '4', '5', '6'], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5], dtype = np.float32)
a

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
a.dtype

dtype('float32')

In [ ]:
a = np.array([1.1, 2.3, 3, 4, 5], dtype = np.int32)
a

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a

array([1, 2, 3, 4, 5], dtype=int32)

## **Type Casting**

In [ ]:
# Type casting means changing the data type of array values.

In [ ]:
a = np.array([0, 1, 2, 3])
a.dtype

dtype('int64')

In [ ]:
new_a = a.astype(np.float64)
new_a

array([0., 1., 2., 3.])

In [ ]:
new_a.dtype

dtype('float64')

In [ ]:
new_a2 = new_a.astype(np.int64)
new_a2

array([0, 1, 2, 3])

In [ ]:
new_a2.dtype

dtype('int64')

In [ ]:
# Type casting error
# in typecasting we cann't covert string into int & float
a = np.array(["1", "2", "hello"])
a_2 = a.astype(np.int64)
a_2

ValueError: invalid literal for int() with base 10: np.str_('hello')

## **Array Properties**

In [ ]:
a = np.array(2)
a

In [ ]:
a.ndim

In [ ]:
a = np.array([0, 1, 2, 3])
a

In [ ]:
a.ndim

In [ ]:
a = np.array([[0, 1, 2, 3,], [4, 5, 6, 7]])
a

In [ ]:
a.ndim

In [ ]:
a = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
a

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.itemsize

## **Array Reshaping**

In [ ]:
# It means changing the shape of an array (rows/columns layout) without changing the data.

In [ ]:
# reshape
a = np.array([0, 1, 2, 3, 4, 5])
reshape = a.reshape(3, 2)
reshape

In [ ]:
reshape2 = reshape.reshape(2, 3)
reshape2

In [ ]:
# ravel() → converts array into 1D, but returns a view (original array change ho sakta hai)
ravel = reshape2.ravel()
ravel

In [ ]:
ravel[3] = 100
print(ravel)
print(reshape2)

In [ ]:
# flatten() → converts array into 1D, but returns a copy (original safe rehta hai)
flat = reshape2.flatten()
flat

In [ ]:
flat[3] = 3

In [ ]:
flat

In [ ]:
reshape2

## **Arithmetic Operations on Arrays**

In [ ]:
# NumPy lets you do math on arrays element by element.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [ ]:
# addition
print(a + b)

In [ ]:
# subtraction
print(b - a)

In [ ]:
# division
print(a/b)

In [ ]:
# int divide
print(b//a)

In [ ]:
# multiplication
print(a*b)

In [ ]:
# modulus
print(a%b)

In [ ]:
# power
print(a**2)

## **Universal Functions**

In [ ]:
# Ufunc = function that does math element-wise on arrays.
# It works on each element of the array automatically.

In [ ]:
a = np.array([1, 4, 9, 16, 25])

In [ ]:
# square root
print(np.sqrt(a))

In [ ]:
# exponential
print(np.exp([0, 1, 2]))

In [ ]:
# sine
print(np.sin(a))

In [ ]:
# sine
angles = np.array([0, np.pi, np.pi/2])
print(np.sin(angles))

In [ ]:
# Absolute value
b =np.array([-1, -2, -3])
print(np.abs(b))

In [ ]:
# np.maximum()

In [ ]:
# np.minimum()

## **Indexing & Slicing**

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7]

### **Indexing**

In [ ]:
# Indexing means getting one specific element from an array using its position number.
# Index always starts from 0.

In [ ]:
print(a[0])

In [ ]:
print(a[-1])

In [ ]:
print(a[5])

In [ ]:
# index arrays -> advance indexing

In [ ]:
# np.take() selects elements from an array using given index numbers.
# np.take -> built in function to perform indexing and slicing.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
ind = [0, 2]
print(np.take(arr, ind))

In [ ]:
ind = [1,3]
print(np.take(arr, ind))

In [ ]:
ind = [-1, -3]
print(np.take(arr, ind))

In [ ]:
ind = [-3, -4]
print(np.take(arr, ind))

In [ ]:
# np.nditer() is used to go through each element of a NumPy array one by one.

In [ ]:
arr = np.array([[1, 2], [3, 4]])

In [ ]:
for x in np.nditer(arr):
  print(x, end=" ")

1 2 3 4

In [ ]:
# np.ndenumerate() = iterate through array and give both index and value of each element.

In [ ]:
for ind, x in np.ndenumerate(arr):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4

### **Slicing**

In [ ]:
# Slicing means getting multiple elements (a part of array).

In [ ]:
a[0:3]

In [ ]:
a[0:6:2]

In [ ]:
a[2:5:2]

In [ ]:
a[ : : 2]

In [ ]:
a[: : 3]

In [ ]:
# negative slicing

In [ ]:
a[-1:-3]

In [ ]:
a[-1:-4:-1]

In [ ]:
a[-7:-2]

In [ ]:
a[-2:-7:-2]

In [ ]:
a[-4:-1:-1]

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[: : 2]

In [ ]:
arr[-2]

In [ ]:
arr[-1:-4:-2]

In [ ]:
# Multi dimensional slicing

In [ ]:
matrix = np.array([[2,3,4],
                   [3,2,5],
                   [6,5,3]])

In [ ]:
matrix[0:2, :]

In [ ]:
matrix[1:3, 1:3]

In [ ]:
# or
matrix[1: , 1: ]

In [ ]:
matrix[-3:-1, -3:-2]

In [ ]:
matrix[-2:-1, -2:]

In [ ]:
matrix[-3:-1, -2:]

## **Views & Copies**

In [ ]:
# View: A view shares the same data with the original array.
# If you change the view → original array also changes.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
view = arr[1:3]
view

array([2, 3])

In [ ]:
view[0] = 199
view

array([199,   3])

In [ ]:
arr

array([  1, 199,   3,   4,   5,   6,   7])

In [ ]:
# Copy: A copy makes new separate data.
# If you change the copy → original array does NOT change.

In [ ]:
copy = arr[1:3].copy()
copy

array([199,   3])

In [ ]:
copy[0] = 2
copy

array([2, 3])

In [ ]:
arr

array([  1, 199,   3,   4,   5,   6,   7])

## **Transpose()**

In [ ]:
# transpose() changes rows into columns and columns into rows.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
print(arr.transpose())

[[1 3]
 [2 4]]

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print(arr.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]

## **Swapaxes()**

In [ ]:
# np.swapaxes() swaps (changes) the positions of two axes in an array.

In [ ]:
arr = np.array([[[1, 2], [3, 4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr, 0, 2)
swap.shape

(2, 2, 1)

## **Concatenation()**

In [ ]:
# Concatenation means joining two or more arrays together.

In [ ]:
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])

In [ ]:
combine = np.concatenate([a, b])
combine

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
c = np.array([8, 9, 10])

In [ ]:
combine_2 = np.concatenate([combine, c])
combine_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Vstack() & Hstack()**

In [ ]:
# np.vstack() joins arrays vertically (one array on top of another).

In [ ]:
X = np.array([[0, 1], [2, 3]])
Y = np.array([[4, 5], [6, 7]])

In [ ]:
print(np.vstack((X, Y)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

In [ ]:
# np.hstack() joins arrays horizontally (side by side).

In [ ]:
print(np.hstack((X, Y)))

[[0 1 4 5]
 [2 3 6 7]]

In [ ]:
# np.stack() joins arrays and creates a new dimension.
# np.stack(arrays, axis=0)
# axis = 0 is row, axis = 1 is column

In [ ]:
print(np.stack((X, Y), axis = 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

In [ ]:
print(np.stack((X, Y), axis = 1))

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]

## **Splitting Arrays**

In [ ]:
# Splitting means dividing one array into multiple smaller arrays.

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
print(np.split(a, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# np.hsplit(): Split array by columns (horizontal split).

In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])

In [ ]:
print(np.hsplit(a, 2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

In [ ]:
# np.vsplit(): Split array by rows (vertical split).

In [ ]:
a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

In [ ]:
print(np.vsplit(a, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

## **Repeating**

In [ ]:
# Repeating means showing the same element multiple times in an array.

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(np.repeat(a, 2))

[1 1 2 2 3 3]

In [ ]:
print(np.repeat(a, 3))

[1 1 1 2 2 2 3 3 3]

## **Tile**

In [ ]:
# tile() repeats the whole array multiple times.

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(np.tile(a, 2))

[1 2 3 1 2 3]

In [ ]:
print(np.tile(a, 3))

[1 2 3 1 2 3 1 2 3]

## **Aggregate Functions**

In [ ]:
# Aggregate functions calculate a single value from many elements in an array.

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
print(np.sum(a))

10

In [ ]:
print(np.min(a))

1

In [ ]:
print(np.max(a))

4

In [ ]:
print(np.mean(a))

2.5

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
print(np.sum(a, axis=1))

[ 6 15 24]

In [ ]:
print(np.sum(a, axis=0))

[12 15 18]

In [ ]:
print(np.min(a, axis=1))

[1 4 7]

In [ ]:
print(np.max(a, axis=0))

[7 8 9]

## **Cumulative Operations**

In [ ]:
# Cumulative operation means values are added or calculated step-by-step from the start of the array.

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
print(np.cumsum(a))

[ 1  3  6 10 15]

In [ ]:
print(np.cumprod(a))

[  1   2   6  24 120]

## **Conditional Based Choice**

In [ ]:
# Conditional choice means selecting values based on a condition.

In [ ]:
# np.where() = choose values based on a condition.

In [ ]:
a = np.array([10, 20, 30, 40])

In [ ]:
result = np.where(a < 25, "Small", "Big")

In [ ]:
print(result)

['Small' 'Small' 'Big' 'Big']

In [ ]:
# np.argwhere() returns the indexes (positions) where a condition is true.

In [ ]:
a = np.array([10, 20, 30, 40])

In [ ]:
print(np.argwhere(a < 25))

[[0]
 [1]]

In [ ]:
print(np.argwhere(a > 25))

[[2]
 [3]]

In [ ]:
# Advanced Conditional: Advanced conditional means applying multiple conditions to filter or select values from an array.

In [ ]:
# Logical conditions = rules applied to array elements to check True or False.

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
result = np.logical_and(a > 20, a < 75)
print(result)

[False False  True  True  True  True  True False]

In [ ]:
result = np.logical_or(a > 20, a < 75)
print(result)

[ True  True  True  True  True  True  True  True]

In [ ]:
result = np.logical_not(a > 20, a < 75)
print(result)

[ True  True False False False False False False]

In [ ]:
result = np.logical_xor(a > 20, a < 75)
print(result)

[ True  True False False False False False  True]

In [ ]:
# Logical operators

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# AND
print(a[(a > 20) & (a < 50)])

[30 40]

In [ ]:
# OR
print(a[(a < 20) | (a > 50)])

[10 60 70 80]

In [ ]:
# NOT
print([~(a > 30)])

[array([ True,  True,  True, False, False, False, False, False])]

In [ ]:
# Condition on Matrix (2D Array)
a = np.array([[10,20,30],
              [40,50,60]])

In [ ]:
print((np.argwhere(a > 15)))

[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]

In [ ]:
print(a[(a > 20)])

[30 40 50 60]

## **Function/Concept**

In [ ]:
# Boolean Mask: Use a condition to create True/False array and select elements.

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
mask = a > 25

In [ ]:
print(mask)

[False False  True  True  True  True  True  True]

In [ ]:
print(a[mask])

[30 40 50 60 70 80]

In [ ]:
# np.take(): Select elements using indexes (like advanced indexing).

In [ ]:
ind = [0, 2, 4, 6]

In [ ]:
print(np.take(a, ind))

[10 30 50 70]

In [ ]:
# np.nonzero(): Returns indexes of elements that are non-zero or True.

In [ ]:
print(np.nonzero(a > 30))

(array([3, 4, 5, 6, 7]),)

## **Boradcasting**

In [ ]:
# Broadcasting = NumPy automatically expands smaller arrays to match the shape of bigger arrays for element-wise operations.

In [ ]:
# Rules of Broadcasting:
# 1. Compare shapes from right to left
# 2. Dimensions are compatible if:
          # 1. They are equal, or
          # 2. One of them is 1
# 3. If not compatible → error

In [ ]:
# Example 1: 1D + 1D
a = np.array([1,2,3])
b = np.array([10,20,30])

In [ ]:
print(a + b)

[11 22 33]

In [ ]:
# Example 2: 1D + 2D
a = np.array([1,2,3])
b = np.array([[10,10,10],
              [20,20,20]])

In [ ]:
print(a + b)

[[11 12 13]
 [21 22 23]]

In [ ]:
a = np.array([[1],[2],[3]])  # shape (3,1)
b = np.array([10,20,30])     # shape (3,)

In [ ]:
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]

In [ ]:
img = np.array([[200, 150], [100, 250]])

In [ ]:
img

array([[200, 150],
       [100, 250]])

In [ ]:
img.shape

(2, 2)

In [ ]:
brightness = img + 50

In [ ]:
brightness

array([[250, 200],
       [150, 300]])

## **Vectorization**

In [ ]:
# Vectorization = perform operations on whole arrays at once without using loops.

In [ ]:
# Pros:
# 1. Faster
#       Operates on whole arrays at once → no explicit Python loops
# 2. Cleaner code
#       Less code, easier to read
# 3. Leverages NumPy optimizations
#       NumPy uses compiled C code under the hood

In [ ]:
# Cons:
# 1. Memory usage
#         Operates on whole arrays → can use more memory for large arrays
# 2. Not always faster for very small arrays
#         Overhead of vectorization may outweigh the benefit
# 3. Limited flexibility
#         Complex logic might need loops or other approaches

In [ ]:
# Example 1: Without vectorization (using loop)
a = np.array([1,2,3,4,5])
b = np.zeros(5)

In [ ]:
for i in range(len(a)):
  b[i] = a[i] * 2

In [ ]:
print(b)

[ 2.  4.  6.  8. 10.]

In [ ]:
# Example 2: With vectorization (using NumPy)

In [ ]:
a = np.array([1,2,3,4,5])
b = a * 2   # vectorized operation

In [ ]:
print(b)

[ 1  4  9 16 25]

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
def square(x):
  return x * x
vfunc = np.vectorize(square)

In [ ]:
print(vfunc(a))

[ 1  4  9 16 25]

## **Dealing with missing values**

In [ ]:
# np.nan -> not a number

In [ ]:
a = np.array([1, 2, np.nan, 4])

In [ ]:
a

array([ 1.,  2., nan,  4.])

In [ ]:
# np.inf and -np.inf -> +ve and -ve infinites

In [ ]:
# np.isnan
# np.isinf
# np.isfinite
# --->these are the functions use to detect any null values, infinite and finite value.

In [ ]:
print(np.isnan(a))

[False False  True False]

In [ ]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [ ]:
print(np.isinf(b))

[False False  True False False]

In [ ]:
new_b = np.nan_to_num(b) # remove nan/infinite values.

In [ ]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])

In [ ]:
# Example: Detecting and Replacing Missing Values

In [ ]:
# Array with missing values (np.nan)
a = np.array([1, 2, np.nan, 4, 5])

In [ ]:
# Detect missing values
print(np.isnan(a))

[False False  True False False]

In [ ]:
# Replace np.nan with 0
a[np.isnan(a)] = 0
print(a)

[1. 2. 0. 4. 5.]

# **8. PANDAS**

In [ ]:
# Pandas is a Python library used to analyze, clean, and organize data easily.

In [ ]:
import pandas as pd

In [ ]:
# why pandas?
#   import datasets -> csv, excel, sql
#   data cleaning -> missing values & invalid values
#   sizemutability
#   reshaping and pivoting od datasets
#   efficent manipulation & extraction
#   statiscal analysis

In [ ]:
# In pandas, there are two primary data structures:

## **1. Series**

In [ ]:
# Series is a one-dimensional data structure.
# It stores data in a single column with index labels.

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30, 40, 50]) # If all values are numbers → numeric type
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s = pd.Series([10, 20, 30, 40, 50, "abc"]) # If numbers + text together → object type
s

0     10
1     20
2     30
3     40
4     50
5    abc
dtype: object

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s.name = "calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [ ]:
s.name

'numbers'

In [ ]:
# indexing
s[0]

np.int64(10)

In [ ]:
s[0:3]

0    10
1    20
2    30
Name: numbers, dtype: int64

In [ ]:
s[2:5]

2    30
3    40
4    50
Name: numbers, dtype: int64

In [ ]:
# iloc -> location based indexing
# iloc (integer location) is used to select data from a DataFrame or Series using row and column index numbers.

In [ ]:
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[[0, 2, 4]]

0    10
2    30
4    50
Name: calories, dtype: int64

In [ ]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]

In [ ]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
# loc -> label based indexing
# In pandas, loc is used to select data using labels (names) instead of index numbers.

In [ ]:
s['banana']

np.int64(20)

In [ ]:
# in label based indexing your start as well as stop value both are included in the output.

In [ ]:
s["banana":"orange"]

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [ ]:
s[["apple", "banana", "orange"]]

apple     10
banana    20
orange    40
Name: calories, dtype: int64

In [ ]:
fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# Conditonal Selection: conditional selection means selecting data based on a condition (like >, <, == etc.).

In [ ]:
s2 > 1

Avocado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
Pomegranate      True
Mango           False
Cherries        False
Name: Protein, dtype: bool

In [ ]:
s2[s2 > 1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [ ]:
# Logical Operators: & (AND), | (OR), and ~ (NOT

In [ ]:
# AND
s2[((s2 > 0.5) & (s2 < 2))]

Oranges        0.9
Banana         1.1
Kiwi           1.1
Pomegranate    1.7
Mango          0.8
Cherries       1.0
Name: Protein, dtype: float64

In [ ]:
# OR
s2[((s2 > 0.5) | (s2 <= 2))]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# NOT
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [ ]:
# Modyfying the series:

In [ ]:
s2["Mango"] = 2.8

In [ ]:
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
ser.notnull().sum()

np.int64(3)

## **2. DataFrame**

In [ ]:
# DataFrame is a two-dimensional data structure.
# It stores data in rows and columns like a table or Excel sheet.

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}